
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Carlos Nuila
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        setFont(new java.awt.Font("Segoe UI Symbol", 0, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearCampo = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_nombreCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        js_longitud = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        rb_si = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();
        jb_crearCampo = new javax.swing.JButton();
        rb_int = new javax.swing.JRadioButton();
        rb_double = new javax.swing.JRadioButton();
        rb_char = new javax.swing.JRadioButton();
        rb_string = new javax.swing.JRadioButton();
        rb_bool = new javax.swing.JRadioButton();
        buttonGroup_llave = new javax.swing.ButtonGroup();
        buttonGroup_tipo = new javax.swing.ButtonGroup();
        jd_listarCampo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_campos = new javax.swing.JTable();
        jd_modificarCampo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_camposMod = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_nombreCampoMod = new javax.swing.JTextField();
        jb_modify = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rb_intMod = new javax.swing.JRadioButton();
        rb_doubleMod = new javax.swing.JRadioButton();
        rb_charMod = new javax.swing.JRadioButton();
        rb_boolMod = new javax.swing.JRadioButton();
        rb_stringMod = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        js_longitudMod = new javax.swing.JSpinner();
        jd_borrarCampo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_camposDlt = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jb_deleteField = new javax.swing.JButton();
        buttonGroup_llaveMod = new javax.swing.ButtonGroup();
        buttonGroup_tipoMod = new javax.swing.ButtonGroup();
        VentanaRegistros = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla_agregarRegistros = new javax.swing.JTable();
        jb_GuardarRegistros = new javax.swing.JButton();
        jb_AddNewRow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_archivo = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jb_abrir = new javax.swing.JButton();
        jb_cerrar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jp_campo = new javax.swing.JPanel();
        jb_crearCampoJD = new javax.swing.JButton();
        jb_listarCampoJD = new javax.swing.JButton();
        jb_modificarCampoJD = new javax.swing.JButton();
        jb_borrarCampoJD = new javax.swing.JButton();
        jp_registro = new javax.swing.JPanel();
        jp_indice = new javax.swing.JPanel();
        jp_estand = new javax.swing.JPanel();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 20)); // NOI18N
        jLabel3.setText("Crear Campo");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setText("LLave Primaria:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jt_nombreCampo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jPanel3.add(jt_nombreCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setText("Tipo:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, -1));

        js_longitud.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        js_longitud.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        js_longitud.setEnabled(false);
        jPanel3.add(js_longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel7.setText("Longitud:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        buttonGroup_llave.add(rb_si);
        rb_si.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_si.setText("Sí");
        jPanel3.add(rb_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        buttonGroup_llave.add(rb_no);
        rb_no.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_no.setText("No");
        jPanel3.add(rb_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jb_crearCampo.setText("Crear");
        jb_crearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampoMouseClicked(evt);
            }
        });
        jPanel3.add(jb_crearCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 30));

        buttonGroup_tipo.add(rb_int);
        rb_int.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_int.setText("int");
        rb_int.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_intMouseClicked(evt);
            }
        });
        jPanel3.add(rb_int, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        buttonGroup_tipo.add(rb_double);
        rb_double.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_double.setText("double");
        rb_double.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_doubleMouseClicked(evt);
            }
        });
        jPanel3.add(rb_double, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        buttonGroup_tipo.add(rb_char);
        rb_char.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_char.setText("char");
        rb_char.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_charMouseClicked(evt);
            }
        });
        jPanel3.add(rb_char, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        buttonGroup_tipo.add(rb_string);
        rb_string.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_string.setText("String");
        rb_string.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_stringMouseClicked(evt);
            }
        });
        jPanel3.add(rb_string, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        buttonGroup_tipo.add(rb_bool);
        rb_bool.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_bool.setText("boolean");
        rb_bool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_boolMouseClicked(evt);
            }
        });
        jPanel3.add(rb_bool, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        javax.swing.GroupLayout jd_crearCampoLayout = new javax.swing.GroupLayout(jd_crearCampo.getContentPane());
        jd_crearCampo.getContentPane().setLayout(jd_crearCampoLayout);
        jd_crearCampoLayout.setHorizontalGroup(
            jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        jd_crearCampoLayout.setVerticalGroup(
            jd_crearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 20)); // NOI18N
        jLabel8.setText("Listar Campos");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 30));

        jtable_campos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jtable_campos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Longitud", "Llave Primaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtable_campos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 240));

        javax.swing.GroupLayout jd_listarCampoLayout = new javax.swing.GroupLayout(jd_listarCampo.getContentPane());
        jd_listarCampo.getContentPane().setLayout(jd_listarCampoLayout);
        jd_listarCampoLayout.setHorizontalGroup(
            jd_listarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jd_listarCampoLayout.setVerticalGroup(
            jd_listarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_camposMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jl_camposMod.setModel(new DefaultListModel());
        jl_camposMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_camposModMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_camposMod);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 250));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 20)); // NOI18N
        jLabel9.setText("Modificar Campos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 60, 30));

        jt_nombreCampoMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jPanel1.add(jt_nombreCampoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 160, -1));

        jb_modify.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jb_modify.setText("Modificar");
        jb_modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modifyMouseClicked(evt);
            }
        });
        jPanel1.add(jb_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 120, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel12.setText("Tipo:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 50, -1));

        buttonGroup_tipoMod.add(rb_intMod);
        rb_intMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_intMod.setText("int");
        rb_intMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_intModMouseClicked(evt);
            }
        });
        jPanel1.add(rb_intMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        buttonGroup_tipoMod.add(rb_doubleMod);
        rb_doubleMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_doubleMod.setText("double");
        rb_doubleMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_doubleModMouseClicked(evt);
            }
        });
        jPanel1.add(rb_doubleMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        buttonGroup_tipoMod.add(rb_charMod);
        rb_charMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_charMod.setText("char");
        rb_charMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_charModMouseClicked(evt);
            }
        });
        jPanel1.add(rb_charMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        buttonGroup_tipoMod.add(rb_boolMod);
        rb_boolMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_boolMod.setText("boolean");
        rb_boolMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_boolModMouseClicked(evt);
            }
        });
        jPanel1.add(rb_boolMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        buttonGroup_tipoMod.add(rb_stringMod);
        rb_stringMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        rb_stringMod.setText("String");
        rb_stringMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_stringModMouseClicked(evt);
            }
        });
        jPanel1.add(rb_stringMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel13.setText("Longitud:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        js_longitudMod.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        js_longitudMod.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        js_longitudMod.setEnabled(false);
        jPanel1.add(js_longitudMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 60, 30));

        javax.swing.GroupLayout jd_modificarCampoLayout = new javax.swing.GroupLayout(jd_modificarCampo.getContentPane());
        jd_modificarCampo.getContentPane().setLayout(jd_modificarCampoLayout);
        jd_modificarCampoLayout.setHorizontalGroup(
            jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_modificarCampoLayout.setVerticalGroup(
            jd_modificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_camposDlt.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jl_camposDlt.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_camposDlt);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 200, 180));

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 20)); // NOI18N
        jLabel11.setText("Borrar Campos");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, 30));

        jb_deleteField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jb_deleteField.setText("Borrar");
        jb_deleteField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_deleteFieldMouseClicked(evt);
            }
        });
        jPanel5.add(jb_deleteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 70, -1));

        javax.swing.GroupLayout jd_borrarCampoLayout = new javax.swing.GroupLayout(jd_borrarCampo.getContentPane());
        jd_borrarCampo.getContentPane().setLayout(jd_borrarCampoLayout);
        jd_borrarCampoLayout.setHorizontalGroup(
            jd_borrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_borrarCampoLayout.setVerticalGroup(
            jd_borrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Tabla_agregarRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Tabla_agregarRegistros);

        jb_GuardarRegistros.setText("Guardar");
        jb_GuardarRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_GuardarRegistrosMouseClicked(evt);
            }
        });

        jb_AddNewRow.setText("Add New Row");
        jb_AddNewRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AddNewRowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VentanaRegistrosLayout = new javax.swing.GroupLayout(VentanaRegistros.getContentPane());
        VentanaRegistros.getContentPane().setLayout(VentanaRegistrosLayout);
        VentanaRegistrosLayout.setHorizontalGroup(
            VentanaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_GuardarRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_AddNewRow, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        VentanaRegistrosLayout.setVerticalGroup(
            VentanaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VentanaRegistrosLayout.createSequentialGroup()
                        .addComponent(jb_AddNewRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_GuardarRegistros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_salvar.setText("Salvar");
        jb_salvar.setEnabled(false);
        jb_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salvarMouseClicked(evt);
            }
        });

        jb_abrir.setText("Abrir");
        jb_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrirMouseClicked(evt);
            }
        });

        jb_cerrar.setText("Cerrar");
        jb_cerrar.setEnabled(false);
        jb_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cerrarMouseClicked(evt);
            }
        });

        jb_salir.setText("Salir del Programa");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        jButton1.setText("Crear Registro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_archivoLayout = new javax.swing.GroupLayout(jp_archivo);
        jp_archivo.setLayout(jp_archivoLayout);
        jp_archivoLayout.setHorizontalGroup(
            jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_archivoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_archivoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_archivoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jp_archivoLayout.setVerticalGroup(
            jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_archivoLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_archivoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jb_salir))
                    .addGroup(jp_archivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Archivo", jp_archivo);

        jb_crearCampoJD.setText("Crear");
        jb_crearCampoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCampoJDMouseClicked(evt);
            }
        });

        jb_listarCampoJD.setText("Listar");
        jb_listarCampoJD.setEnabled(false);
        jb_listarCampoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarCampoJDMouseClicked(evt);
            }
        });

        jb_modificarCampoJD.setText("Modificar");
        jb_modificarCampoJD.setEnabled(false);
        jb_modificarCampoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarCampoJDMouseClicked(evt);
            }
        });

        jb_borrarCampoJD.setText("Borrar");
        jb_borrarCampoJD.setEnabled(false);
        jb_borrarCampoJD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarCampoJDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_campoLayout = new javax.swing.GroupLayout(jp_campo);
        jp_campo.setLayout(jp_campoLayout);
        jp_campoLayout.setHorizontalGroup(
            jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_campoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_crearCampoJD, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jb_modificarCampoJD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_borrarCampoJD, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jb_listarCampoJD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jp_campoLayout.setVerticalGroup(
            jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_campoLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crearCampoJD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_listarCampoJD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificarCampoJD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_borrarCampoJD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        jTabbedPane1.addTab("Campos", jp_campo);

        javax.swing.GroupLayout jp_registroLayout = new javax.swing.GroupLayout(jp_registro);
        jp_registro.setLayout(jp_registroLayout);
        jp_registroLayout.setHorizontalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jp_registroLayout.setVerticalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registros", jp_registro);

        javax.swing.GroupLayout jp_indiceLayout = new javax.swing.GroupLayout(jp_indice);
        jp_indice.setLayout(jp_indiceLayout);
        jp_indiceLayout.setHorizontalGroup(
            jp_indiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jp_indiceLayout.setVerticalGroup(
            jp_indiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Índices", jp_indice);

        javax.swing.GroupLayout jp_estandLayout = new javax.swing.GroupLayout(jp_estand);
        jp_estand.setLayout(jp_estandLayout);
        jp_estandLayout.setHorizontalGroup(
            jp_estandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jp_estandLayout.setVerticalGroup(
            jp_estandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estandarización", jp_estand);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        // TODO add your handling code here:
        if (jb_nuevo.isEnabled()) {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
            jfc.addChoosableFileFilter(filtro);
            jfc.setAcceptAllFileFilterUsed(false);
            int seleccion = jfc.showSaveDialog(this);
            FileWriter fw = null;
            BufferedWriter bw = null;
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                try {
                    archivoActual = null;
                    archivoActual = new RandomAccessFile(jfc.getSelectedFile().getPath() + ".txt", "rw");
                    metaData = new Metadata();
                    JOptionPane.showMessageDialog(this, "El archivo se ha creado exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                    jTabbedPane1.setEnabledAt(1, true);
                    jTabbedPane1.setEnabledAt(2, true);
                    jTabbedPane1.setEnabledAt(3, true);
                    jTabbedPane1.setEnabledAt(4, true);
                    jb_nuevo.setEnabled(false);
                    jb_abrir.setEnabled(false);
                    jb_cerrar.setEnabled(true);
                    jb_salvar.setEnabled(true);
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cerrarMouseClicked
        // TODO add your handling code here:
        if (jb_cerrar.isEnabled()) {
            JOptionPane.showMessageDialog(this, "El archivo se ha cerrado exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            try {
                archivoActual.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            archivoActual = null;
            metaData = null;
            jb_nuevo.setEnabled(true);
            jb_abrir.setEnabled(true);
            jb_cerrar.setEnabled(false);
            jb_salvar.setEnabled(false);
            jTabbedPane1.setEnabledAt(1, false);
            jTabbedPane1.setEnabledAt(2, false);
            jTabbedPane1.setEnabledAt(3, false);
            jTabbedPane1.setEnabledAt(4, false);
            jb_modificarCampoJD.setEnabled(false);
            jb_borrarCampoJD.setEnabled(false);
            jb_listarCampoJD.setEnabled(false);
        }
    }//GEN-LAST:event_jb_cerrarMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_crearCampoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampoJDMouseClicked
        // TODO add your handling code here:
        if (metaData.getCampos().size() <= 14) {
            jt_nombreCampo.setText("");
            rb_int.setSelected(true);
            rb_bool.setSelected(false);
            rb_char.setSelected(false);
            rb_double.setSelected(false);
            rb_string.setSelected(false);
            js_longitud.setValue(16);
            if (buscarLlave()) {
                rb_si.setSelected(false);
                rb_si.setEnabled(false);
                rb_no.setSelected(true);
            } else {
                rb_si.setEnabled(true);
                rb_si.setSelected(false);
                rb_no.setSelected(true);
            }
            jd_crearCampo.pack();
            jd_crearCampo.setModal(true);
            jd_crearCampo.setLocationRelativeTo(this);
            jd_crearCampo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ha creado 15 campos, no se pueden crear más", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jb_crearCampoJDMouseClicked

    private void jb_modificarCampoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarCampoJDMouseClicked
        // TODO add your handling code here:{
        if (jb_modificarCampoJD.isEnabled() && registros.isEmpty()) {
            jl_camposMod.setModel(new DefaultListModel());
            DefaultListModel modelo = (DefaultListModel) jl_camposMod.getModel();
            for (int i = 0; i < metaData.getCampos().size(); i++) {
                modelo.addElement(metaData.getCampos().get(i));
            }
            jl_camposMod.setModel(modelo);

            jt_nombreCampoMod.setText("");

            jd_modificarCampo.pack();
            jd_modificarCampo.setModal(true);
            jd_modificarCampo.setLocationRelativeTo(this);
            jd_modificarCampo.setVisible(true);
        }
    }//GEN-LAST:event_jb_modificarCampoJDMouseClicked

    private void jb_borrarCampoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarCampoJDMouseClicked
        // TODO add your handling code here:
        if (jb_borrarCampoJD.isEnabled()) {
            jl_camposDlt.setModel(new DefaultListModel());
            DefaultListModel modelo = (DefaultListModel) jl_camposDlt.getModel();
            for (int i = 0; i < metaData.getCampos().size(); i++) {
                modelo.addElement(metaData.getCampos().get(i));
            }
            jl_camposDlt.setModel(modelo);

            jd_borrarCampo.pack();
            jd_borrarCampo.setModal(true);
            jd_borrarCampo.setLocationRelativeTo(this);
            jd_borrarCampo.setVisible(true);
        }
    }//GEN-LAST:event_jb_borrarCampoJDMouseClicked

    private void jb_crearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCampoMouseClicked
        // TODO add your handling code here:
        String nombreCampo = jt_nombreCampo.getText();
        String tipoCampo = "";
        if (rb_int.isSelected()) {
            tipoCampo = "int";
        }
        if (rb_double.isSelected()) {
            tipoCampo = "double";
        }
        if (rb_char.isSelected()) {
            tipoCampo = "char";
        }
        if (rb_string.isSelected()) {
            tipoCampo = "String";
        }
        if (rb_bool.isSelected()) {
            tipoCampo = "boolean";
        }
        int longitud = (int) js_longitud.getValue();
        boolean llave = false;
        if (rb_si.isSelected()) {
            llave = true;
        }

        if (metaData.getCampos().size() <= 14) {
            Campo nuevoCampo = new Campo(nombreCampo, tipoCampo, longitud, llave);
            metaData.getCampos().add(nuevoCampo);
            JOptionPane.showMessageDialog(jd_crearCampo, "El campo se ha creado exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jd_crearCampo, "Ya ha creado el máximo de campos que es 15", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

        jt_nombreCampo.setText("");
        rb_int.setSelected(true);
        rb_bool.setSelected(false);
        rb_char.setSelected(false);
        rb_double.setSelected(false);
        rb_string.setSelected(false);
        js_longitud.setValue(16);
        if (buscarLlave()) {
            rb_si.setEnabled(false);
            rb_no.setSelected(true);
        } else {
            rb_si.setEnabled(true);
            rb_si.setSelected(true);
            rb_no.setSelected(false);
        }
        if (metaData.getCampos().size() == 1) {
            jb_listarCampoJD.setEnabled(true);
            jb_borrarCampoJD.setEnabled(true);
            jb_modificarCampoJD.setEnabled(true);
        }
    }//GEN-LAST:event_jb_crearCampoMouseClicked

    private void jb_listarCampoJDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarCampoJDMouseClicked
        // TODO add your handling code here:
        if (jb_listarCampoJD.isEnabled()) {
            jtable_campos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
            jtable_campos.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Nombre", "Tipo", "Longitud", "Llave Primaria"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            jScrollPane1.setViewportView(jtable_campos);

            jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 240));

            Campo campoActual;
            for (int i = 0; i < metaData.getCampos().size(); i++) {
                campoActual = (Campo) metaData.getCampos().get(i);
                Object[] newRow = {
                    campoActual.getNombre(),
                    campoActual.getTipo(),
                    campoActual.getLength(),
                    campoActual.isLlavePrimaria()
                };
                DefaultTableModel modelo = (DefaultTableModel) jtable_campos.getModel();
                modelo.addRow(newRow);
                jtable_campos.setModel(modelo);
            }
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtable_campos.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtable_campos.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtable_campos.getColumnModel().getColumn(2).setCellRenderer(tcr);

            jd_listarCampo.pack();
            jd_listarCampo.setModal(true);
            jd_listarCampo.setLocationRelativeTo(this);
            jd_listarCampo.setVisible(true);
        }
    }//GEN-LAST:event_jb_listarCampoJDMouseClicked

    private void jb_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salvarMouseClicked
        // TODO add your handling code here:
        if (jb_salvar.isEnabled()) {
            try {
                metaData.escribirCampos(archivoActual);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Se ha guardado exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jb_salvarMouseClicked

    private void rb_stringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_stringMouseClicked
        // TODO add your handling code here:
        if (rb_string.isSelected()) {
            js_longitud.setValue(0);
            js_longitud.setEnabled(true);
        }
    }//GEN-LAST:event_rb_stringMouseClicked

    private void rb_intMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_intMouseClicked
        // TODO add your handling code here:
        if (rb_int.isSelected()) {
            js_longitud.setValue(16);
            js_longitud.setEnabled(false);
        }
    }//GEN-LAST:event_rb_intMouseClicked

    private void rb_doubleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_doubleMouseClicked
        // TODO add your handling code here:
        if (rb_double.isSelected()) {
            js_longitud.setValue(64);
            js_longitud.setEnabled(false);
        }
    }//GEN-LAST:event_rb_doubleMouseClicked

    private void rb_charMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_charMouseClicked
        // TODO add your handling code here:
        if (rb_char.isSelected()) {
            js_longitud.setValue(8);
            js_longitud.setEnabled(false);
        }
    }//GEN-LAST:event_rb_charMouseClicked

    private void rb_boolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_boolMouseClicked
        // TODO add your handling code here:
        if (rb_bool.isSelected()) {
            js_longitud.setValue(8);
            js_longitud.setEnabled(false);
        }
    }//GEN-LAST:event_rb_boolMouseClicked

    private void jb_abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrirMouseClicked
        // TODO add your handling code here:
        if (jb_abrir.isEnabled()) {
            archivoActual = null;
            try {
                JFileChooser jfc = new JFileChooser("./");
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "txt");
                jfc.addChoosableFileFilter(filtro);
                jfc.setAcceptAllFileFilterUsed(false);
                int seleccion = jfc.showOpenDialog(this);
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    archivoActual = new RandomAccessFile(jfc.getSelectedFile(), "rw");
                    metaData = new Metadata();
                    jTabbedPane1.setEnabledAt(1, true);
                    jTabbedPane1.setEnabledAt(2, true);
                    jTabbedPane1.setEnabledAt(3, true);
                    jTabbedPane1.setEnabledAt(4, true);
                    jb_nuevo.setEnabled(false);
                    jb_abrir.setEnabled(false);
                    jb_cerrar.setEnabled(true);
                    jb_salvar.setEnabled(true);
                    metaData.cargarCampos(archivoActual);
                    if (!metaData.getCampos().isEmpty()) {
                        jb_listarCampoJD.setEnabled(true);
                        jb_modificarCampoJD.setEnabled(true);
                        jb_borrarCampoJD.setEnabled(true);
                    }
                    JOptionPane.showMessageDialog(this, "El archivo se ha abierto exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jb_abrirMouseClicked

    private void jl_camposModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_camposModMouseClicked
        // TODO add your handling code here:
        if (jl_camposMod.getSelectedIndex() >= 0) {
            int index = jl_camposMod.getSelectedIndex();
            jt_nombreCampoMod.setText(metaData.getCampos().get(index).getNombre());
            if (metaData.getCampos().get(index).getTipo().equals("int")) {
                rb_intMod.setSelected(true);
            }
            if (metaData.getCampos().get(index).getTipo().equals("double")) {
                rb_doubleMod.setSelected(true);
            }
            if (metaData.getCampos().get(index).getTipo().equals("char")) {
                rb_charMod.setSelected(true);
            }
            if (metaData.getCampos().get(index).getTipo().equals("String")) {
                rb_stringMod.setSelected(true);
            }
            if (metaData.getCampos().get(index).getTipo().equals("boolean")) {
                rb_boolMod.setSelected(true);
            }
            js_longitudMod.setValue(metaData.getCampos().get(index).getLength());
        }
    }//GEN-LAST:event_jl_camposModMouseClicked

    private void jb_modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modifyMouseClicked
        // TODO add your handling code here:
        if (jl_camposMod.getSelectedIndex() >= 0) {
            int index = jl_camposMod.getSelectedIndex();
            metaData.getCampos().get(index).setNombre(jt_nombreCampoMod.getText());
            metaData.getCampos().get(index).setLength((int) js_longitudMod.getValue());
            String tipoCampo = "";
            if (rb_intMod.isSelected()) {
                tipoCampo = "int";
            }
            if (rb_doubleMod.isSelected()) {
                tipoCampo = "double";
            }
            if (rb_charMod.isSelected()) {
                tipoCampo = "char";
            }
            if (rb_stringMod.isSelected()) {
                tipoCampo = "String";
            }
            if (rb_boolMod.isSelected()) {
                tipoCampo = "boolean";
            }
            metaData.getCampos().get(index).setTipo(tipoCampo);

            jl_camposMod.setModel(new DefaultListModel());
            DefaultListModel modelo = (DefaultListModel) jl_camposMod.getModel();
            for (int i = 0; i < metaData.getCampos().size(); i++) {
                modelo.addElement(metaData.getCampos().get(i));
            }
            jl_camposMod.setModel(modelo);

            jt_nombreCampoMod.setText("");
            rb_boolMod.setSelected(false);
            rb_charMod.setSelected(false);
            rb_doubleMod.setSelected(false);
            rb_intMod.setSelected(false);
            rb_stringMod.setSelected(false);
            js_longitudMod.setValue(0);

            JOptionPane.showMessageDialog(jd_modificarCampo, "Se ha modificado el campo exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe tener un campo seleccionado en la lista");
        }
    }//GEN-LAST:event_jb_modifyMouseClicked

    private void jb_deleteFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_deleteFieldMouseClicked
        // TODO add your handling code here:
        if (jl_camposDlt.getSelectedIndex() >= 0) {
            metaData.getCampos().remove(jl_camposDlt.getSelectedIndex());

            jl_camposDlt.setModel(new DefaultListModel());
            DefaultListModel modelo = (DefaultListModel) jl_camposDlt.getModel();
            for (int i = 0; i < metaData.getCampos().size(); i++) {
                modelo.addElement(metaData.getCampos().get(i));
            }
            jl_camposDlt.setModel(modelo);

            JOptionPane.showMessageDialog(jd_borrarCampo, "Se ha eliminado el campo exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            if (metaData.getCampos().isEmpty()) {
                jb_modificarCampoJD.setEnabled(false);
                jb_listarCampoJD.setEnabled(false);
                jd_borrarCampo.dispose();
                jb_borrarCampoJD.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe tener un campo seleccionado en la lista");
        }
    }//GEN-LAST:event_jb_deleteFieldMouseClicked

    private void rb_intModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_intModMouseClicked
        // TODO add your handling code here:
        if (rb_intMod.isSelected()) {
            js_longitudMod.setValue(16);
            js_longitudMod.setEnabled(false);
        }
    }//GEN-LAST:event_rb_intModMouseClicked

    private void rb_doubleModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_doubleModMouseClicked
        // TODO add your handling code here:
        if (rb_doubleMod.isSelected()) {
            js_longitudMod.setValue(64);
            js_longitudMod.setEnabled(false);
        }
    }//GEN-LAST:event_rb_doubleModMouseClicked

    private void rb_charModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_charModMouseClicked
        // TODO add your handling code here:
        if (rb_charMod.isSelected()) {
            js_longitudMod.setValue(8);
            js_longitudMod.setEnabled(false);
        }
    }//GEN-LAST:event_rb_charModMouseClicked

    private void rb_boolModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_boolModMouseClicked
        // TODO add your handling code here:
        if (rb_boolMod.isSelected()) {
            js_longitudMod.setValue(8);
            js_longitudMod.setEnabled(false);
        }
    }//GEN-LAST:event_rb_boolModMouseClicked

    private void rb_stringModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_stringModMouseClicked
        // TODO add your handling code here:
        if (rb_stringMod.isSelected()) {
            js_longitudMod.setValue(0);
            js_longitudMod.setEnabled(true);
        }
    }//GEN-LAST:event_rb_stringModMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        VentanaRegistros.pack();
        VentanaRegistros.setLocationRelativeTo(VentanaRegistros);
        VentanaRegistros.setModal(true);
        VentanaRegistros.setVisible(true);
        Tabla_agregarRegistros.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{}
        ));
        DefaultTableModel modelo = (DefaultTableModel) Tabla_agregarRegistros.getModel();
        int data[] = new int[10];
        String cabezas[] = new String[metaData.getCampos().size()];
        for (int i = 0; i < cabezas.length; i++) {
            cabezas[i] = metaData.getCampos().get(i).getNombre();
        }
        for (Object a : cabezas) {
            modelo.addColumn(a);
        }

        String row[] = new String[metaData.getCampos().size()];
        modelo.addRow(row);
        Tabla_agregarRegistros.setModel(modelo);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_AddNewRowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AddNewRowMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) Tabla_agregarRegistros.getModel();
        String row[] = new String[metaData.getCampos().size()];
        modelo.addRow(row);
        Tabla_agregarRegistros.setModel(modelo);
    }//GEN-LAST:event_jb_AddNewRowMouseClicked

    private void jb_GuardarRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_GuardarRegistrosMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) Tabla_agregarRegistros.getModel();
        int rows = modelo.getRowCount(),columns = modelo.getColumnCount();
        Object data[][] = new String[rows][columns];
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                data[i][j] = modelo.getValueAt(i,j);
            }
        }
        //////////////
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                System.out.println(data[i][j]);
            }
        }
    }//GEN-LAST:event_jb_GuardarRegistrosMouseClicked

    public boolean buscarLlave() {
        for (int i = 0; i < metaData.getCampos().size(); i++) {
            if (metaData.getCampos().get(i).isLlavePrimaria()) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    //revisar salvar despues de borrar
    RandomAccessFile archivoActual;
    Metadata metaData;
    ArrayList<String> registros = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_agregarRegistros;
    private javax.swing.JDialog VentanaRegistros;
    private javax.swing.ButtonGroup buttonGroup_llave;
    private javax.swing.ButtonGroup buttonGroup_llaveMod;
    private javax.swing.ButtonGroup buttonGroup_tipo;
    private javax.swing.ButtonGroup buttonGroup_tipoMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_AddNewRow;
    private javax.swing.JButton jb_GuardarRegistros;
    private javax.swing.JButton jb_abrir;
    private javax.swing.JButton jb_borrarCampoJD;
    private javax.swing.JButton jb_cerrar;
    private javax.swing.JButton jb_crearCampo;
    private javax.swing.JButton jb_crearCampoJD;
    private javax.swing.JButton jb_deleteField;
    private javax.swing.JButton jb_listarCampoJD;
    private javax.swing.JButton jb_modificarCampoJD;
    private javax.swing.JButton jb_modify;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JDialog jd_borrarCampo;
    private javax.swing.JDialog jd_crearCampo;
    private javax.swing.JDialog jd_listarCampo;
    private javax.swing.JDialog jd_modificarCampo;
    private javax.swing.JList<String> jl_camposDlt;
    private javax.swing.JList<String> jl_camposMod;
    private javax.swing.JPanel jp_archivo;
    private javax.swing.JPanel jp_campo;
    private javax.swing.JPanel jp_estand;
    private javax.swing.JPanel jp_indice;
    private javax.swing.JPanel jp_registro;
    private javax.swing.JSpinner js_longitud;
    private javax.swing.JSpinner js_longitudMod;
    private javax.swing.JTextField jt_nombreCampo;
    private javax.swing.JTextField jt_nombreCampoMod;
    private javax.swing.JTable jtable_campos;
    private javax.swing.JRadioButton rb_bool;
    private javax.swing.JRadioButton rb_boolMod;
    private javax.swing.JRadioButton rb_char;
    private javax.swing.JRadioButton rb_charMod;
    private javax.swing.JRadioButton rb_double;
    private javax.swing.JRadioButton rb_doubleMod;
    private javax.swing.JRadioButton rb_int;
    private javax.swing.JRadioButton rb_intMod;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JRadioButton rb_string;
    private javax.swing.JRadioButton rb_stringMod;
    // End of variables declaration//GEN-END:variables
}
