
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos Nuila
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
        setFont(new java.awt.Font("Segoe UI Symbol", 0, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevoArchivo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombreArchivo = new javax.swing.JTextField();
        jb_crearArchivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_archivo = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_salvar = new javax.swing.JButton();
        jb_cerrar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jp_campo = new javax.swing.JPanel();
        jp_registro = new javax.swing.JPanel();
        jp_indice = new javax.swing.JPanel();
        jp_estand = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 20)); // NOI18N
        jLabel1.setText("Crear Archivo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jt_nombreArchivo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jPanel1.add(jt_nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, -1));

        jb_crearArchivo.setText("Crear");
        jb_crearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearArchivoMouseClicked(evt);
            }
        });
        jPanel1.add(jb_crearArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        javax.swing.GroupLayout jd_nuevoArchivoLayout = new javax.swing.GroupLayout(jd_nuevoArchivo.getContentPane());
        jd_nuevoArchivo.getContentPane().setLayout(jd_nuevoArchivoLayout);
        jd_nuevoArchivoLayout.setHorizontalGroup(
            jd_nuevoArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        jd_nuevoArchivoLayout.setVerticalGroup(
            jd_nuevoArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_salvar.setText("Salvar");
        jb_salvar.setEnabled(false);

        jb_cerrar.setText("Cerrar");
        jb_cerrar.setEnabled(false);
        jb_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cerrarMouseClicked(evt);
            }
        });

        jb_salir.setText("Salir del Programa");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_archivoLayout = new javax.swing.GroupLayout(jp_archivo);
        jp_archivo.setLayout(jp_archivoLayout);
        jp_archivoLayout.setHorizontalGroup(
            jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_archivoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jb_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jp_archivoLayout.setVerticalGroup(
            jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_archivoLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        jTabbedPane1.addTab("Archivo", jp_archivo);

        javax.swing.GroupLayout jp_campoLayout = new javax.swing.GroupLayout(jp_campo);
        jp_campo.setLayout(jp_campoLayout);
        jp_campoLayout.setHorizontalGroup(
            jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jp_campoLayout.setVerticalGroup(
            jp_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Campos", jp_campo);

        javax.swing.GroupLayout jp_registroLayout = new javax.swing.GroupLayout(jp_registro);
        jp_registro.setLayout(jp_registroLayout);
        jp_registroLayout.setHorizontalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jp_registroLayout.setVerticalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registros", jp_registro);

        javax.swing.GroupLayout jp_indiceLayout = new javax.swing.GroupLayout(jp_indice);
        jp_indice.setLayout(jp_indiceLayout);
        jp_indiceLayout.setHorizontalGroup(
            jp_indiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jp_indiceLayout.setVerticalGroup(
            jp_indiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Índices", jp_indice);

        javax.swing.GroupLayout jp_estandLayout = new javax.swing.GroupLayout(jp_estand);
        jp_estand.setLayout(jp_estandLayout);
        jp_estandLayout.setHorizontalGroup(
            jp_estandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jp_estandLayout.setVerticalGroup(
            jp_estandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estandarización", jp_estand);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        // TODO add your handling code here:
        jd_nuevoArchivo.pack();
        jd_nuevoArchivo.setModal(true);
        jd_nuevoArchivo.setVisible(true);
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_crearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearArchivoMouseClicked
        // TODO add your handling code here:
        String nombreArchivo = "./Archivos/"+jt_nombreArchivo.getText()+".txt";
        archivoActual = new File(nombreArchivo);
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(archivoActual, false);
            bw = new BufferedWriter(fw);
            bw.write("");
            bw.flush();
        } catch (Exception e) {
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jt_nombreArchivo.setText("");
        JOptionPane.showMessageDialog(this, "Se ha creado exitosamente el archivo", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        jd_nuevoArchivo.setVisible(false);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(3, true);
        jTabbedPane1.setEnabledAt(4, true);
        jb_nuevo.setEnabled(false);
        jb_cerrar.setEnabled(true);
        jb_salvar.setEnabled(true);
    }//GEN-LAST:event_jb_crearArchivoMouseClicked

    private void jb_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cerrarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Se ha cerrado el archivo", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        archivoActual = null;
        jb_nuevo.setEnabled(true);
        jb_cerrar.setEnabled(false);
        jb_salvar.setEnabled(false);
    }//GEN-LAST:event_jb_cerrarMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jb_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void escribirArchivo() throws IOException {
        
    }
    

    File archivoActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_cerrar;
    private javax.swing.JButton jb_crearArchivo;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JDialog jd_nuevoArchivo;
    private javax.swing.JPanel jp_archivo;
    private javax.swing.JPanel jp_campo;
    private javax.swing.JPanel jp_estand;
    private javax.swing.JPanel jp_indice;
    private javax.swing.JPanel jp_registro;
    private javax.swing.JTextField jt_nombreArchivo;
    // End of variables declaration//GEN-END:variables
}
